defaults: &defaults
  APPID: "wx94eac922bbda0127"
  APPSECRET: "db9996995a940ca1c07f823493a271ad"
  HOST: "https://9e491ca0.ngrok.io"
  WeixinTokenString: "8f67d8759e78b265d23c2fec"
  WeixinSecretString: "FYQr4MI-I67TD6tiyEI0Hdv7knI0h_Vp"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults