defaults: &defaults
  APPID: "wx8cbc369ae3d74887"
  APPSECRET: "6f719d088020a1ed5b6dbf8eda94c2b4"
  HOST: "http://www.easehui.com"
  WeixinTokenString: "529f2ed084b685624be3bde1"
  WeixinSecretString: "ReWckhxChahsXgBR9TWMaeH66-qqvzK0"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults