# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00da807ee8d8b820eb8cec78f55cadf334db1492f6f32af9b8f45d6e3011cb59b9c84439bb328f6716d97859acc00b91f79ac3e6a824a0c834291e02af0657c5

test:
  secret_key_base: aba0b3759ce354873a6972237c9e545bb36ecc500c419aa881c694be94b2f0d8f2bd5b298ffb37cd34987434a1da9df7d66ee0e479009e8b835d9002d11bb616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
